SurveyDonkey.WEB/Controllers/SurveyPageController.cs
using Newtonsoft.Json;
using SurveyDonkey.API.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;

namespace SurveyDonkey.WEB.Controllers
{
    public class SurveyPageController : Controller
    {
        private string baseUrl = "http://localhost:5471/api/v1/";
        // GET: SurveyPage
        [HttpGet]
        public ActionResult Index()
        {
            List<SurveyTemplate> surveyTemplateObject = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseUrl);

                //HTTP GET
                var result = client.GetAsync("surveytemplates").Result.Content.ReadAsStringAsync().Result;

                surveyTemplateObject = JsonConvert.DeserializeObject<List<SurveyTemplate>>(result);
            }

            //by default always use first template
            return View(surveyTemplateObject[0]);
        }

        // POST: SurveyPage/Create
        [System.Web.Http.HttpPost]
        public ActionResult Create(SurveyTemplate myNewSurvey)
        {
            try
            {
                var responsesList = new List<Response>();
                foreach (var question in myNewSurvey.QuestionsList)
                {
                    foreach (var response in question.ResponsesList)
                    {
                        if (response.IsSelected)
                        {
                            responsesList.Add(new Response
                            {
                                Contents = response.Contents,
                                ResponseTemplateId = response.TemplateId,
                                QuestionTemplateId = response.QuestionTemplateId
                            });
                        }
                    }
                }

                var respondedSurvey = new Survey
                {
                    CreatedTimeStamp = DateTime.Now,
                    SurveyTemplateId = myNewSurvey.SurveyTemplateId,
                    Responses = responsesList
                };

                //post survey
                //*************************************************************
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(baseUrl);

                    //HTTP POST
                    var content = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(respondedSurvey)));
                    content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    var result = client.PostAsync("survey", content).Result;
                }

                //rerturn to brand new survey
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SurveyDonkey.WEB/Controllers/SurveyStatsController.cs
using Newtonsoft.Json;
using SurveyDonkey.API.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Mvc;
using System.Web.Routing;

namespace SurveyDonkey.WEB.Controllers
{
    

    public class SurveyStatsController : Controller
    {
        private string baseUrl = "http://localhost:5471/api/v1/";

        private SurveyStats surveyTemplateObject = null;

        // GET: SurveyStats
        public ActionResult Index()
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseUrl);

                //HTTP GET
                var result = client.GetAsync("surveystats").Result.Content.ReadAsStringAsync().Result;

                surveyTemplateObject = JsonConvert.DeserializeObject<SurveyStats>(result);
            }

            //by default always use first template
            return View(surveyTemplateObject);
        }

        public ActionResult DrawChart(string jsonValues)
        {
            if (jsonValues == null)
            {
                return View();
            }

            Dictionary<string, int> values = new Dictionary<string, int>();
            foreach (var item in JsonConvert.DeserializeObject<Dictionary<string, int>>(jsonValues))
            {
                values.Add(item.Key, item.Value);
            } 

            return View(values);
        }
    }
}

SurveyDonkey.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SurveyDonkey</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("To Survey", "Index", "SurveyPage", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("To Statistics", "Index", "SurveyStats", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SurveyDonkey ASP.NET Application</p>
        </footer>
    </div>   
</body>
</html>

SurveyDonkey.WEB/Views/SurveyPage/Index.cshtml
@model SurveyDonkey.API.Models.SurveyTemplate

@{
    ViewBag.Title = "Surveys";
}

<h2>@Model.SurveyName</h2>

@using (Html.BeginForm("Create", "SurveyPage", FormMethod.Post))
{
    @Html.HiddenFor(m => m.SurveyTemplateId)

    <ol>
        @{
            //count questions to create unique id for controls inside partial views
            int questionCounter = 0;
            foreach (var question in Model.QuestionsList)
            {
                if (question.QuestionType == SurveyDonkey.Common.QuestionType.Scale)
                {
                    <li>@Html.Partial("_RangeResponse", Model, new ViewDataDictionary { { "QuestionCounter", @questionCounter } })<br /></li>
                }

                else if (question.QuestionType == SurveyDonkey.Common.QuestionType.FreeText)
                {
                    <li>@Html.Partial("_FreeTextResponse", Model, new ViewDataDictionary { { "QuestionCounter", @questionCounter } })<br /></li>
                }

                else if (question.QuestionType == SurveyDonkey.Common.QuestionType.MultiChoice)
                {
                    <li>@Html.Partial("_MultiResponse", Model, new ViewDataDictionary { { "QuestionCounter", @questionCounter } })<br /></li>
                }

                else //create single response type for any other options
                {
                    <li>@Html.Partial("_SingleResponse", Model, new ViewDataDictionary { { "QuestionCounter", @questionCounter } })<br /></li>
                }
               
                questionCounter++;
            }
        }

    </ol>


    <button type="submit" id="SubmitSurveyBtn">DONE</button>    
}

SurveyDonkey.WEB/Views/SurveyPage/_FreeTextResponse.cshtml
@model SurveyDonkey.API.Models.SurveyTemplate

@*<h3>Range Response Here</h3>*@

@Model.QuestionsList[ViewBag.QuestionCounter].Content

<div id="Question_@(ViewBag.QuestionCounter)">
    @{
        int questionNumber = ViewBag.QuestionCounter;

        @Html.TextAreaFor(m => m.QuestionsList[questionNumber].ResponsesList[0].Contents, htmlAttributes: new { rows = 10, cols = 40, style = "width: 70%; max-width: 70%;" });
        @Html.HiddenFor(m => m.QuestionsList[questionNumber].ResponsesList[0].TemplateId)
        @Html.HiddenFor(m => m.QuestionsList[questionNumber].ResponsesList[0].QuestionTemplateId)
        @Html.HiddenFor(m => m.QuestionsList[questionNumber].ResponsesList[0].IsSelected, "true")
    }
</div>
<div><button id="@(ViewBag.QuestionCounter)_GoToNextQuestionBtn" style="visibility:hidden">OK</button></div>

<script type="text/javascript">
    $("div[id='Question_@(ViewBag.QuestionCounter)']").keyup(function () {
        if ($("div[id='Question_@(ViewBag.QuestionCounter)']").find('textarea').val().length > 0) {
            $('#@(ViewBag.QuestionCounter)_GoToNextQuestionBtn').css("visibility", "visible");
            $("div[id='Question_@(ViewBag.QuestionCounter)']").find('input[id*="_IsSelected"]').val(true);
        } else {
            $('#@(ViewBag.QuestionCounter)_GoToNextQuestionBtn').css("visibility", "hidden");
            $("div[id='Question_@(ViewBag.QuestionCounter)']").find('input[id*="_IsSelected"]').val(false);
        }
    });
</script>

SurveyDonkey.WEB/Views/SurveyPage/_MultiResponse.cshtml
@model SurveyDonkey.API.Models.SurveyTemplate

@*<h3>Multi Response Here</h3>*@

@Model.QuestionsList[ViewBag.QuestionCounter].Content
<ul style="list-style-type:none;columns: 2;-webkit-columns: 2;-moz-columns: 2;">

    @{
        int questionNumber = ViewBag.QuestionCounter;

        for (int i = 0; i < Model.QuestionsList[questionNumber].ResponsesList.Count; i++)
        {
            <li>
                @Html.CheckBoxFor(m => m.QuestionsList[questionNumber].ResponsesList[i].IsSelected, "true")
                @Html.LabelFor(m => m.QuestionsList[questionNumber].ResponsesList[i].Contents, Model.QuestionsList[questionNumber].ResponsesList[i].Contents)
                @Html.HiddenFor(m => m.QuestionsList[questionNumber].ResponsesList[i].TemplateId, Model.QuestionsList[questionNumber].ResponsesList[i].TemplateId)
                @Html.HiddenFor(m => m.QuestionsList[questionNumber].ResponsesList[i].QuestionTemplateId, Model.QuestionsList[questionNumber].ResponsesList[i].QuestionTemplateId)
            </li>
        }
    }

</ul>

SurveyDonkey.WEB/Views/SurveyPage/_RangeResponse.cshtml
@model SurveyDonkey.API.Models.SurveyTemplate

@*<h3>Range Response Here</h3>*@

@Model.QuestionsList[ViewBag.QuestionCounter].Content

<table id="Question_@(ViewBag.QuestionCounter)">
    <tr>
        @{
            int questionNumber = ViewBag.QuestionCounter;
            for (int index = 0; index < Model.QuestionsList[questionNumber].ResponsesList.Count; index++)
            {
                var id = ViewBag.QuestionCounter + "_" + index.ToString();

        <td align="center" id=@id>
            @Html.DisplayFor(m => m.QuestionsList[questionNumber].ResponsesList[index].Contents)
            @Html.HiddenFor(m => m.QuestionsList[questionNumber].ResponsesList[index].IsSelected, "true")
            @Html.HiddenFor(m => m.QuestionsList[questionNumber].ResponsesList[index].TemplateId)
            @Html.HiddenFor(m => m.QuestionsList[questionNumber].ResponsesList[index].QuestionTemplateId)

        </td>
            }
        }
    </tr>
</table>



<style>
    table {
        width: 100%;
        margin: auto;
    }

        table tr td {
            border: 1px solid;
        }

    .selected {
        background: #60ff00;
    }

    td {
        /*width: 30%;*/
        position: relative;
        padding-top: 0;
        padding-bottom: 0;
        outline: 1px solid #ccc;
    }

        td:after {
            content: '';
            display: block;
            margin-top: 100%;
        }

        td .content {
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
        }

    table, td {
        border: 1px solid black;
    }
</style>

<script type="text/javascript">
    jQuery(function ($) {
        var cells = $("table[id='Question_@(ViewBag.QuestionCounter)']").find("td[id*='@(ViewBag.QuestionCounter)_']")

        // handle click and add class
        cells.on("click", function () {
            $(cells).removeClass("selected");
            $(this).addClass("selected");
            $(cells).find('input[id*="_IsSelected"]').val(false);
            $(this).find('input[id*="_IsSelected"]').val(true);
        })
    });
</script>

SurveyDonkey.WEB/Views/SurveyPage/_SingleResponse.cshtml
@model SurveyDonkey.API.Models.SurveyTemplate

@*<h3>Single Response Here</h3>*@

@Model.QuestionsList[ViewBag.QuestionCounter].Content
<ul style="list-style-type:none;columns: 2;-webkit-columns: 2;-moz-columns: 2;">
    <div id="Question_@(ViewBag.QuestionCounter)">
        @{
            int questionNumber = ViewBag.QuestionCounter;

            for (int i = 0; i < Model.QuestionsList[questionNumber].ResponsesList.Count; i++)
            {
                <li>
                    @Html.RadioButtonFor(m => m.QuestionsList[questionNumber].ResponsesList[i].IsSelected, "true")
                    @Html.LabelFor(m => m.QuestionsList[questionNumber].ResponsesList[i].Contents, Model.QuestionsList[questionNumber].ResponsesList[i].Contents)
                    @Html.HiddenFor(m => m.QuestionsList[questionNumber].ResponsesList[i].TemplateId, Model.QuestionsList[questionNumber].ResponsesList[i].TemplateId)
                    @Html.HiddenFor(m => m.QuestionsList[questionNumber].ResponsesList[i].QuestionTemplateId, Model.QuestionsList[questionNumber].ResponsesList[i].QuestionTemplateId)
                </li>
            }
        }
    </div>
</ul>
<script type="text/javascript">
    jQuery(function ($) {
        var radios = $("div[id='Question_@(ViewBag.QuestionCounter)']").find("[type=radio]")

        // handle click and add class
        radios.on("click", function () {
            $(radios).prop('checked',false)
            $(this).prop('checked', true)
        })
    });
</script>

SurveyDonkey.WEB/Views/SurveyStats/DrawChart.cshtml
@model Dictionary<string, int>

@{
    var myChart = new Chart(width: 600, height: 400, theme: ChartTheme.Green)
    .AddSeries("", "Column", null, null, null, 1, Model.Keys.ToArray(), null, Model.Values.ToArray(), null);
    myChart.Write();
}

SurveyDonkey.WEB/Views/SurveyStats/Index.cshtml
@model SurveyDonkey.API.Models.SurveyStats

@{
    ViewBag.Title = "Statistics";
}

<h2>Survey Statistics</h2>

@{
    int questionCounter = 0;
    foreach (var questionStats in Model.QuestionStats)
    {
        if (questionStats.QuestionTypeId != SurveyDonkey.Common.QuestionType.FreeText)
        {
            @Html.Partial("_EnumeratedQuestion", Model, new ViewDataDictionary { { "QuestionCounter", @questionCounter } })<br />
        }
        else
        {
            @Html.Partial("_FreeTextQuestion", Model, new ViewDataDictionary { { "QuestionCounter", @questionCounter } })<br />
        }

        questionCounter++;
    }
}

SurveyDonkey.WEB/Views/SurveyStats/_EnumeratedQuestion.cshtml
@model SurveyDonkey.API.Models.SurveyStats

<h3>@*Enumerated Response Here*@</h3>

@{
    int questionCounter = ViewBag.QuestionCounter;

    <h3>@Model.QuestionStats[questionCounter].Contents</h3>

    var responsesStats = Model.QuestionStats[questionCounter].ResponsesStats.ResponsesStats;

    <img src="@Url.Action("DrawChart", new { jsonValues = Newtonsoft.Json.JsonConvert.SerializeObject(responsesStats) })" />
}

SurveyDonkey.WEB/Views/SurveyStats/_FreeTextQuestion.cshtml
@model SurveyDonkey.API.Models.SurveyStats

@*<h3>Free Text Response Here</h3>*@

@{
    int questionCounter = ViewBag.QuestionCounter;

    <h3>@Model.QuestionStats[questionCounter].Contents</h3>

    <h4>Responses:</h4>

    foreach (var value in @Model.QuestionStats[questionCounter].ResponsesStats.ResponsesStats.Keys)
    {
        <h5>@value</h5>
    }

}